gcp_credentials: ENCRYPTED[9cf993f6cc2ab666aa2d428185257608d065f6468146aaa26d6d2f31e88ed8045d7dd615cd5c7c83d7bcf12578762869]

task:
  name: build
  gke_container:
    image: gradle:jdk8
    cluster_name: cirrus-ci-cluster
    zone: us-central1-a
    namespace: default
    cpu: 3
    memory: 10Gb
  gradle_cache:
    folder: ~/.gradle/caches
  script:
    - printenv
    - gradle build --parallel --no-daemon
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
